// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBa63FrVudvN2W2wlMh9FfbreoAzDBxEM',
    appId: '1:1084591897200:web:ac30bc75a6d0b0070ed2b5',
    messagingSenderId: '1084591897200',
    projectId: 'admin-panel-e08dd',
    authDomain: 'admin-panel-e08dd.firebaseapp.com',
    storageBucket: 'admin-panel-e08dd.appspot.com',
    measurementId: 'G-5HHN0QQVKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkzf-zPDHTnZlArUGy7tQyovZ2jE4us84',
    appId: '1:1084591897200:android:7ecb9a4d333a6b1a0ed2b5',
    messagingSenderId: '1084591897200',
    projectId: 'admin-panel-e08dd',
    storageBucket: 'admin-panel-e08dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpL8w7uJUwYJfvPP2QWpEyoBSCos4A_Qg',
    appId: '1:1084591897200:ios:dd9a0a51787e81b00ed2b5',
    messagingSenderId: '1084591897200',
    projectId: 'admin-panel-e08dd',
    storageBucket: 'admin-panel-e08dd.appspot.com',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpL8w7uJUwYJfvPP2QWpEyoBSCos4A_Qg',
    appId: '1:1084591897200:ios:c2fead09f661747a0ed2b5',
    messagingSenderId: '1084591897200',
    projectId: 'admin-panel-e08dd',
    storageBucket: 'admin-panel-e08dd.appspot.com',
    iosBundleId: 'com.example.adminPanel.RunnerTests',
  );
}
